
require 'mongoid'

KANBANERY_API_TOKEN = ENV['KANBANERY_API_TOKEN']
KANBANERY_ORGANIZATION= ENV['KANBANERY_ORGANIZATION']

KANBANERY_API_URL = "https://#{KANBANERY_ORGANIZATION}.kanbanery.com/api/v1/"
