development:
  sessions:
    default:
      database: rufino_api_development
      hosts: localhost

test:
  sessions:
    default:
      database: rufino_api_test
      hosts: localhost

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
